### ISSUE TITLE
blueocean plugin question

### ISSUE THREAD

**Issue by marcus-sds** [FINkit/jenkins-boshrelease#127]
Hello, is it possible to install blueocean plugin?

**Comment by rigoford** [comment]
Hi there Marcus.

Thanks for your question. The short answer is yes.

However, it's not something we'll do immediately as it's not a plugin we (currently) want to use. So, we'll add some functionality that will allow plugins to be disabled, likely by using an ops file that will effectively generate `JENKINS_HOME/plugins/PLUGIN_NAME.hpi.disabled` files for any plugins you don't want to use.

Please check back in a week or so.

Cheers

Martin

**Comment by marcus-sds** [comment]
Thanks. Also persistent disk option seems to be omitted at default manifest
file.

**Comment by danieljamesrees** [comment]
Hi @marcus-sds ,

Apologies for taking much longer than a week to get back to you. One of my colleagues has now included the Blue Ocean plugin in our Jenkins blob, as of release [0.0.105](https://github.com/FINkit/jenkins-boshrelease/releases/tag/v0.0.105).

We also added an operations file, [add-persistent-disks.yml](https://github.com/FINkit/jenkins-boshrelease/blob/master/operations/add-persistent-disks.yml), in release [0.0.106](https://github.com/FINkit/jenkins-boshrelease/releases/tag/v0.0.106) as an example of how operators can add persistent disks to the Jenkins Master and Agent nodes. We didn't include it in the manifest included with this repository, as it's not part of our default usage.

I'll close this Issue now, but please feel free to raise another if you have any queries or problems regarding the releases.

Kind Regards,

Dan
